# Generated by Django 5.2.1 on 2025-07-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_remove_companionpost_report_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companionpost',
            name='region',
            field=models.CharField(blank=True, choices=[('서울', '서울'), ('경기', '경기'), ('부산', '부산'), ('대구', '대구'), ('인천', '인천'), ('광주', '광주'), ('대전', '대전'), ('울산', '울산'), ('강원', '강원'), ('충북', '충북'), ('충남', '충남'), ('전북', '전북'), ('전남', '전남'), ('경북', '경북'), ('경남', '경남'), ('제주', '제주'), ('기타', '기타')], max_length=20, null=True, verbose_name='지역'),
        ),
    ]
