# Generated by Django 4.2.21 on 2025-07-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_blockedstatuspost_blockedsharingpost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companionpost',
            name='report_count',
            field=models.PositiveIntegerField(default=0, verbose_name='신고 횟수'),
        ),
        migrations.AddField(
            model_name='exchangereview',
            name='report_count',
            field=models.PositiveIntegerField(default=0, verbose_name='신고 횟수'),
        ),
        migrations.AddField(
            model_name='proxypost',
            name='report_count',
            field=models.PositiveIntegerField(default=0, verbose_name='신고 횟수'),
        ),
        migrations.AddField(
            model_name='sharingpost',
            name='report_count',
            field=models.PositiveIntegerField(default=0, verbose_name='신고 횟수'),
        ),
        migrations.AddField(
            model_name='statuspost',
            name='report_count',
            field=models.PositiveIntegerField(default=0, verbose_name='신고 횟수'),
        ),
    ]
