# Generated by Django 4.2.21 on 2025-07-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_companionpost_report_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companionpost',
            name='status',
            field=models.CharField(choices=[('모집중', '모집중'), ('모집완료', '모집완료'), ('진행중', '진행중'), ('완료', '완료')], default='모집중', max_length=10, verbose_name='모집 상태'),
        ),
        migrations.AlterField(
            model_name='proxypost',
            name='status',
            field=models.CharField(choices=[('모집중', '모집중'), ('긴급모집', '긴급모집'), ('마감', '마감'), ('완료', '완료')], max_length=20, verbose_name='모집상태'),
        ),
    ]
