# Generated by Django 5.2.1 on 2025-07-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupFT', '0005_userrelation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='report_count',
            field=models.PositiveIntegerField(default=0, verbose_name='신고당한 횟수'),
        ),
        migrations.AddField(
            model_name='user',
            name='reported_by',
            field=models.TextField(blank=True, default='', verbose_name='신고당한 횟수'),
        ),
    ]
