# Generated by Django 5.2.1 on 2025-07-11 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signupFT', '0005_userrelation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('exchange', '교환'), ('sale', '판매'), ('proxy', '대리구매'), ('companion', '동행'), ('inquiry', '문의')], max_length=20)),
                ('post_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message', models.TextField(blank=True, null=True)),
                ('last_timestamp', models.DateTimeField(blank=True, null=True)),
                ('guest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_as_guest', to='signupFT.user')),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_as_host', to='signupFT.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('send_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='signupFT.user')),
                ('room', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatting.chatroom')),
            ],
        ),
    ]
