# Generated by Django 4.2.21 on 2025-07-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photocard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocard',
            name='place',
            field=models.CharField(choices=[('올림픽공원', '올림픽공원'), ('상암', '상암'), ('더현대', '더현대'), ('광야', '광야'), ('인스파이어', '인스파이어'), ('홍대', '홍대')], max_length=20, null=True),
        ),
    ]
