# Generated by Django 5.2.1 on 2025-07-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photocard', '0011_delete_tempidol_delete_tempuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocard',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='photocard',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
